# Generated by Django 3.0.5 on 2020-05-07 03:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trainingsession.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.UUIDField(default=uuid.uuid4)),
                ('state', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('script', models.FileField(default='', upload_to=trainingsession.models.upload_to_user)),
                ('searcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
