# Generated by Django 3.0.5 on 2020-05-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingsession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='batch_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='epochs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='loss',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='metrics',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='optimizer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='session_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='state',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
